OrderHandler.UI/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using OrderHandler.Data;
using OrderHandler.UI.Models;
using OrderHandler.Core.Models;
using OrderHandler.Core.Services;
using AutoMapper;
using System.Linq;

namespace OrderHandler.UI.Controllers
{
    public class ArticleController : Controller
    {
        public IArticleService _articleContext { get; set; }

        public IMapper _mapper;

        public ArticleController(IArticleService articleContext, IMapper mapper)
        {
            this._articleContext = articleContext;
            this._mapper = mapper;
        }

        // GET: OrderRowController
        public async Task<IActionResult> Index()
        {
            try
            {
                var articles = await _articleContext.GetAllArticles();

                var articlesModels = _mapper.Map<IEnumerable<Article>, IEnumerable<ArticleViewModel>>(articles);

                return View(articlesModels.AsQueryable());
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex);
                throw;
            }
        }
    }
}

OrderHandler.UI/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OrderHandler.Core.Models;
using OrderHandler.Core.Services;
using OrderHandler.Data;
using OrderHandler.UI.Helpers;
using OrderHandler.UI.Models;

namespace OrderHandler.UI.Controllers
{
    public class OrderController : Controller
    {
        public IOrderService _orderContext { get; set; }

        public IArticleService _articleContext { get; set; }

        public IOrderRowService _orderRowContext { get; set; }

        public IMapper _mapper;

        public OrderController(IOrderService orderContext,
                               IArticleService articleContext,
                               IOrderRowService orderRowContext,
                               IMapper mapper)
        {
            this._orderContext = orderContext;
            this._articleContext = articleContext;
            this._orderRowContext = orderRowContext;
            this._mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var orders = await _orderContext.GetAllOrders();

                var autoMappedOrders = _mapper.Map<IEnumerable<Order>, IEnumerable<OrderViewModel>>(orders);

                return View(autoMappedOrders);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                throw;
            }
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(OrderViewModel order)
        {
            try
            {
                var orderToCreate = _mapper.Map<OrderViewModel, Order>(order);

                int id = await _orderContext.CreateOrder(orderToCreate);

                return RedirectToAction("CreateOrderRowByOrderId", new { orderId = id });
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                throw;
            }
        }

        public IActionResult CreateOrderRowByOrderId(int orderId)
        {
            return View("CreateOrderRow", new OrderRowViewModel { OrderId = orderId });
        }

        [HttpPost]
        public async Task<IActionResult> CreateOrderRowByOrderId(OrderRowViewModel orderRow)
        {
            try
            {
                Article articleToCreate = await _articleContext.GetIfArticleByNameExist(orderRow.ArticleName);

                if (articleToCreate != null)
                {
                    articleToCreate.Id = articleToCreate.Id;

                    orderRow.ArticleNumber = articleToCreate.ArticleNumber;
                }

                if (articleToCreate is null)
                {
                    articleToCreate = new Article()
                    {
                        ArticleName = orderRow.ArticleName,
                        Price = orderRow.Price,
                        ArticleNumber = orderRow.ArticleNumber
                    };

                    articleToCreate.Id = await _articleContext.CreateArticle(articleToCreate);
                }

                OrderRow orderRowToCreate = new OrderRow()
                {
                    ArticleId = articleToCreate.Id,
                    OrderId = orderRow.OrderId,
                    RowNumber = await _orderRowContext.GetOrderRowNumber(orderRow.OrderId),
                    ArticleAmount = orderRow.ArticleAmount,
                };

                await _orderRowContext.CreateOrderRow(orderRowToCreate);

                return RedirectToAction("Edit", new { id = orderRow.OrderId });
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                throw;
            }
        }

        public async Task<IActionResult> Details(int id)
        {
            try
            {
                Order order = new Order();
                order = await _orderContext.GetOrderById(id);

                OrderRow orderRows = new OrderRow();
                var listOfOrders = await _orderRowContext.GetOrderRowsByOrderId(id);

                OrderViewModel orderView = new OrderViewModel()
                {
                    Id = order.Id,
                    CustomerName = order.CustomerName,
                };

                orderView.OrderRow = new List<OrderRowViewModel>();

                if (listOfOrders.Count > 0)
                {
                    int orderRowNr = 1;

                    foreach (var orderRow in listOfOrders)
                    {
                        orderView.OrderRow.Add(new OrderRowViewModel()
                        {
                            ArticleAmount = orderRow.ArticleAmount,
                            ArticleName = orderRow.Article.ArticleName,
                            ArticleNumber = orderRow.Article.ArticleNumber,
                            Price = orderRow.Article.Price,
                            OrderId = order.Id,
                            OrderSum = OrderHelper.GetOrderSum(orderRow.Article.Price, orderRow.ArticleAmount),
                            OrderRowNr = orderRowNr
                        });

                        orderRowNr++;
                    }
                }
                return View(orderView);

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                throw;
            }

        }

        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                Order order = new Order();
                order = await _orderContext.GetOrderById(id);

                OrderRow orderRows = new OrderRow();
                var listOfOrders = await _orderRowContext.GetOrderRowsByOrderId(id);

                OrderViewModel orderView = new OrderViewModel()
                {
                    Id = order.Id,
                    CustomerName = order.CustomerName,
                };

                orderView.OrderRow = new List<OrderRowViewModel>();

                if (listOfOrders.Count > 0)
                {
                    int orderRowNr = 1;

                    foreach (var orderRow in listOfOrders)
                    {
                        orderView.OrderRow.Add(new OrderRowViewModel()
                        {
                            ArticleAmount = orderRow.ArticleAmount,
                            ArticleName = orderRow.Article.ArticleName,
                            ArticleNumber = orderRow.Article.ArticleNumber,
                            Price = orderRow.Article.Price,
                            OrderId = order.Id,
                            OrderSum = OrderHelper.GetOrderSum(orderRow.Article.Price, orderRow.ArticleAmount),
                            OrderRowNr = orderRowNr
                        });

                        orderRowNr++;
                    }
                }
                return View(orderView);

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                throw;
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Order order)
        {
            try
            {
                var orderToUpdate = await _orderContext.GetOrderById(order.Id);

                await _orderContext.UpdateOrder(orderToUpdate, order);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                throw;
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                return View(await _orderContext.GetOrderById(id));
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                throw;
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Order order)
        {
            try
            {
                await _orderRowContext.DeleteOrderRowsByOrderId(order.Id);

                await _orderContext.DeleteOrder(order);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                throw;
            }
        }
    }
}

OrderHandler.UI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> signInManager;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Order Handler</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/custom.css" />
    <link href="~/Content/MvcGrid/mvc-grid.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="~/css/mvc-grid/mvc-grid.css" rel="stylesheet">
</head>
<body>
    <nav class="site-header sticky-top py-1">
        <div class="container d-flex flex-column flex-md-row justify-content-between">
            <a class="py-2" asp-controller="Home" asp-action="Index" aria-label="Product">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mx-auto" role="img" viewBox="0 0 24 24" focusable="false"><title>Product</title><circle cx="12" cy="12" r="10"></circle><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"></path></svg>
            </a>
            <a class="py-2 d-none d-md-inline-block asp-area=" asp-controller="Order" asp-action="Index">Order</a>
            <a class="py-2 d-none d-md-inline-block asp-area=" asp-controller="Article" asp-action="Index">Articles</a>
            <a class="py-2 d-none d-md-inline-block" asp-controller="Home" asp-action="About">About</a>
            @if (signInManager.IsSignedIn(User))
            {
                <a class="py-2 d-none d-md-inline-block" asp-controller="Account" asp-action="Logout">Log Out</a>
            }
            else
            {
                <a class="py-2 d-none d-md-inline-block" asp-controller="Account" asp-action="Register">Sign Up</a>

                <a class="py-2 d-none d-md-inline-block" asp-controller="Account" asp-action="login">Login</a>
            }
        </div>
    </nav>
    <div class="container-fluid">
        <main>
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/mvc-grid/mvc-grid.js"></script>
    <script>
        document.querySelectorAll(".mvc-grid").forEach(element => new MvcGrid(element));
    </script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/Scripts/MvcGrid/mvc-grid.js"></script>
    @RenderSection("Scripts", required: false)
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <script>
        +[].forEach.call(document.getElementsByClassName('mvc-grid'), function (element) {
            +               new MvcGrid(element);
            +           });
    </script>
</body>
</html>